---
- name: Setup new Ubuntu Github Runner instance
  hosts: default
  vars_files: ./vars.yml
  become: true

  tasks:

### USER AND SSH TASKS ###
  - name: User tasks
    ansible.builtin.include_tasks:
      file: setup-users.yml

### TIME/NTP SETTINGS ###
  - name: Ubuntu set NTP
    ansible.builtin.include_tasks:
      file: ubuntu-set-ntp.yml

### SHELL ###
  - name: Setup interface
    ansible.builtin.include_tasks:
      file: setup-interface.yml

### PACKER + TERRAFORM ###
  - name: Install Packer and Terraform
    ansible.builtin.include_tasks:
      file: setup-packer-terraform.yml

### DOCKER ###
  - name: Install Docker
    ansible.builtin.include_tasks:
      file: setup-docker.yml

### ANSIBLE ###
  - name: Install Ansible
    ansible.builtin.include_tasks:
      file: setup-ansible.yml

### UPDATE CLOUD-INIT ###
  - name: Update cloud-init
    ansible.builtin.include_tasks:
      file: update-cloudinit.yml
