---
name: Auto approve PRs on LGTM

on:
  issue_comment:
    types:
      - created

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/github-script@v7
      name: Approve LGTM Review
      if: github.actor == 'thehedgefrog' &&  contains(github.event.comment.body, 'LGTM')
      with:
        script: |
          github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            review_id: 1,
            event: 'APPROVE',
            body: 'This PR has been approved.'
          })